import {
  Dimensions,
  StatusBar,
  Platform,
  PixelRatio,
  Easing,
  UIManager,
  LayoutAnimation,
} from 'react-native';
import {CardStyleInterpolators} from '@react-navigation/stack';
import {RFPercentage} from 'react-native-responsive-fontsize';
import {
  widthPercentageToDP as wdp,
  heightPercentageToDP as hdp,
} from 'react-native-responsive-screen';

export const WIDTH = Dimensions.get('screen').width;
export const HEIGHT = Dimensions.get('screen').height;

const customWidth = 1133;
const customHeight = 744;

export const IOS = Platform.OS === 'ios';
export const ANDROID = Platform.OS === 'android';

export const FADE = {
  from: {
    opacity: 0,
  },
  to: {
    opacity: 1,
  },
};

export const layoutAnimation = () => {
  if (Platform.OS === 'android') {
    UIManager.setLayoutAnimationEnabledExperimental &&
      UIManager.setLayoutAnimationEnabledExperimental(true);
  }
  LayoutAnimation.configureNext(LayoutAnimation?.Presets?.easeInEaseOut);
};

export const springLayoutAnimation = () => {
  if (Platform.OS === 'android') {
    UIManager.setLayoutAnimationEnabledExperimental &&
      UIManager.setLayoutAnimationEnabledExperimental(true);
  }
  LayoutAnimation.configureNext(LayoutAnimation?.Presets?.spring);
};

export const linearLayoutAnimation = () => {
  if (Platform.OS === 'android') {
    UIManager.setLayoutAnimationEnabledExperimental &&
      UIManager.setLayoutAnimationEnabledExperimental(true);
  }
  LayoutAnimation.configureNext(LayoutAnimation?.Presets?.linear);
};

const transitionSpec = {
  open: {
    animation: 'timing',
    config: {
      duration: 250,
      easing: Easing.inOut(Easing.ease),
    },
  },
  close: {
    animation: 'timing',
    config: {
      duration: 250,
      easing: Easing.inOut(Easing.ease),
    },
  },
};

const springTransitionSpec = {
  open: {
    animation: 'spring',
    config: {
      duration: 250,
      easing: Easing.inOut(Easing.ease),
    },
  },
  close: {
    animation: 'timing',
    config: {
      duration: 250,
      easing: Easing.inOut(Easing.ease),
    },
  },
};

export const BottomSheetTransition = {
  transitionSpec,
  cardStyleInterpolator: CardStyleInterpolators.forBottomSheetAndroid,
};

export const HorizontalTransition = {
  transitionSpec,
  cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS,
};

export const ModalTransition = {
  transitionSpec: springTransitionSpec,
  cardStyleInterpolator: CardStyleInterpolators.forModalPresentationIOS,
};

const widthPercentageToDP = (widthPercent: number | string) => {
  // Parse string percentage input and convert it to number.
  const elemWidth =
    typeof widthPercent === 'number' ? widthPercent : parseFloat(widthPercent);

  // Use PixelRatio.roundToNearestPixel method in order to round the layout
  // size (dp) to the nearest one that correspons to an integer number of pixels.
  return PixelRatio.roundToNearestPixel((WIDTH * elemWidth) / 100);
};

const heightPercentageToDP = (heightPercent: number | string) => {
  // Parse string percentage input and convert it to number.
  const elemHeight =
    typeof heightPercent === 'number'
      ? heightPercent
      : parseFloat(heightPercent);

  // Use PixelRatio.roundToNearestPixel method in order to round the layout
  // size (dp) to the nearest one that correspons to an integer number of pixels.
  return PixelRatio.roundToNearestPixel((HEIGHT * elemHeight) / 100);
};

export const hp = (val: number) => {
  // get scaled height equivalent of design height
  // const num = val / 8.44;
  // return heightPercentageToDP(num);
  const dimension = (val / customHeight) * 100;
  return hdp(`${dimension}%`);
};

export const wp = (val: number) => {
  // get scaled width equivalent of design width
  // const num = val / 3.88;
  // return widthPercentageToDP(num);
  const dimension = (val / customWidth) * 100;
  return wdp(`${dimension}%`);
};

export const fontSz = (val: number) => RFPercentage(val / 8.5);

export const HITSLOP = {
  right: wp(10),
  left: wp(10),
  top: hp(10),
  bottom: hp(10),
};

export const STATUS_BAR_HEIGHT = StatusBar.currentHeight || hp(28);

export const getCloser = (
  value: number | undefined,
  checkOne: number,
  checkTwo: number,
) =>
  Math.abs(value - checkOne) < Math.abs(value - checkTwo) ? checkOne : checkTwo;


  export const countries = [
    { id: "NG", name: "Nigeria" },
    { id: "US", name: "United States" },
    { id: "GB", name: "United Kingdom" },
    { id: "AF", name: "Afghanistan" },
    { id: "AL", name: "Albania" },
    { id: "DZ", name: "Algeria" },
    { id: "AS", name: "American Samoa" },
    { id: "AD", name: "Andorra" },
    { id: "AO", name: "Angola" },
    { id: "AI", name: "Anguilla" },
    { id: "AQ", name: "Antarctica" },
    { id: "AG", name: "Antigua and Barbuda" },
    { id: "AR", name: "Argentina" },
    { id: "AM", name: "Armenia" },
    { id: "AW", name: "Aruba" },
    { id: "AU", name: "Australia" },
    { id: "AT", name: "Austria" },
    { id: "AZ", name: "Azerbaijan" },
    { id: "BS", name: "Bahamas" },
    { id: "BH", name: "Bahrain" },
    { id: "BD", name: "Bangladesh" },
    { id: "BB", name: "Barbados" },
    { id: "BY", name: "Belarus" },
    { id: "BE", name: "Belgium" },
    { id: "BZ", name: "Belize" },
    { id: "BJ", name: "Benin" },
    { id: "BM", name: "Bermuda" },
    { id: "BT", name: "Bhutan" },
    { id: "BO", name: "Bolivia" },
    { id: "BA", name: "Bosnia and Herzegovina" },
    { id: "BW", name: "Botswana" },
    { id: "BR", name: "Brazil" },
    { id: "IO", name: "British Indian Ocean Territory" },
    { id: "VG", name: "British Virgin Islands" },
    { id: "BN", name: "Brunei" },
    { id: "BG", name: "Bulgaria" },
    { id: "BF", name: "Burkina Faso" },
    { id: "BI", name: "Burundi" },
    { id: "KH", name: "Cambodia" },
    { id: "CM", name: "Cameroon" },
    { id: "CA", name: "Canada" },
    { id: "CV", name: "Cape Verde" },
    { id: "KY", name: "Cayman Islands" },
    { id: "CF", name: "Central African Republic" },
    { id: "TD", name: "Chad" },
    { id: "CL", name: "Chile" },
    { id: "CN", name: "China" },
    { id: "CO", name: "Colombia" },
    { id: "KM", name: "Comoros" },
    { id: "CD", name: "Congo (DRC)" },
    { id: "CG", name: "Congo (Republic)" },
    { id: "CK", name: "Cook Islands" },
    { id: "CR", name: "Costa Rica" },
    { id: "HR", name: "Croatia" },
    { id: "CU", name: "Cuba" },
    { id: "CW", name: "Curaçao" },
    { id: "CY", name: "Cyprus" },
    { id: "CZ", name: "Czech Republic" },
    { id: "DK", name: "Denmark" },
    { id: "DJ", name: "Djibouti" },
    { id: "DM", name: "Dominica" },
    { id: "DO", name: "Dominican Republic" },
    { id: "TL", name: "East Timor" },
    { id: "EC", name: "Ecuador" },
    { id: "EG", name: "Egypt" },
    { id: "SV", name: "El Salvador" },
    { id: "GQ", name: "Equatorial Guinea" },
    { id: "ER", name: "Eritrea" },
    { id: "EE", name: "Estonia" },
    { id: "ET", name: "Ethiopia" },
    { id: "FK", name: "Falkland Islands" },
    { id: "FO", name: "Faroe Islands" },
    { id: "FJ", name: "Fiji" },
    { id: "FI", name: "Finland" },
    { id: "FR", name: "France" },
    { id: "PF", name: "French Polynesia" },
    { id: "GA", name: "Gabon" },
    { id: "GM", name: "Gambia" },
    { id: "GE", name: "Georgia" },
    { id: "DE", name: "Germany" },
    { id: "GH", name: "Ghana" },
    { id: "GI", name: "Gibraltar" },
    { id: "GR", name: "Greece" },
    { id: "GL", name: "Greenland" },
    { id: "GD", name: "Grenada" },
    { id: "GU", name: "Guam" },
    { id: "GT", name: "Guatemala" },
    { id: "GN", name: "Guinea" },
    { id: "GW", name: "Guinea-Bissau" },
    { id: "GY", name: "Guyana" },
    { id: "HT", name: "Haiti" },
    { id: "HN", name: "Honduras" },
    { id: "HK", name: "Hong Kong" },
    { id: "HU", name: "Hungary" },
    { id: "IS", name: "Iceland" },
    { id: "IN", name: "India" },
    { id: "ID", name: "Indonesia" },
    { id: "IR", name: "Iran" },
    { id: "IQ", name: "Iraq" },
    { id: "IE", name: "Ireland" },
    { id: "IL", name: "Israel" },
    { id: "IT", name: "Italy" },
    { id: "CI", name: "Ivory Coast" },
    { id: "JM", name: "Jamaica" },
    { id: "JP", name: "Japan" },
    { id: "JO", name: "Jordan" },
    { id: "KZ", name: "Kazakhstan" },
    { id: "KE", name: "Kenya" },
    { id: "KI", name: "Kiribati" },
    { id: "KP", name: "Korea (North)" },
    { id: "KR", name: "Korea (South)" },
    { id: "KW", name: "Kuwait" },
    { id: "KG", name: "Kyrgyzstan" },
    { id: "LA", name: "Laos" },
    { id: "LV", name: "Latvia" },
    { id: "LB", name: "Lebanon" },
    { id: "LS", name: "Lesotho" },
    { id: "LR", name: "Liberia" },
    { id: "LY", name: "Libya" },
    { id: "LI", name: "Liechtenstein" },
    { id: "LT", name: "Lithuania" },
    { id: "LU", name: "Luxembourg" },
    { id: "MO", name: "Macau" },
    { id: "MK", name: "Macedonia" },
    { id: "MG", name: "Madagascar" },
    { id: "MW", name: "Malawi" },
    { id: "MY", name: "Malaysia" },
    { id: "MV", name: "Maldives" },
    { id: "ML", name: "Mali" },
    { id: "MT", name: "Malta" },
    { id: "MH", name: "Marshall Islands" },
    { id: "MR", name: "Mauritania" },
    { id: "MU", name: "Mauritius" },
    { id: "MX", name: "Mexico" },
    { id: "FM", name: "Micronesia" },
    { id: "MD", name: "Moldova" },
    { id: "MC", name: "Monaco" },
    { id: "MN", name: "Mongolia" },
    { id: "ME", name: "Montenegro" },
    { id: "MS", name: "Montserrat" },
    { id: "MA", name: "Morocco" },
    { id: "MZ", name: "Mozambique" },
    { id: "MM", name: "Myanmar" },
    { id: "NA", name: "Namibia" },
    { id: "NR", name: "Nauru" },
    { id: "NP", name: "Nepal" },
    { id: "NL", name: "Netherlands" },
    { id: "NZ", name: "New Zealand" },
    { id: "NI", name: "Nicaragua" },
    { id: "NE", name: "Niger" },
    { id: "NG ", name: "Nigeria" },
    { id: "NU", name: "Niue" },
    { id: "NF", name: "Norfolk Island" },
    { id: "MP", name: "Northern Mariana Islands" },
    { id: "NO", name: "Norway" },
    { id: "OM", name: "Oman" },
    { id: "PK", name: "Pakistan" },
    { id: "PW", name: "Palau" },
    { id: "PS", name: "Palestine" },
    { id: "PA", name: "Panama" },
    { id: "PG", name: "Papua New Guinea" },
    { id: "PY", name: "Paraguay" },
    { id: "PE", name: "Peru" },
    { id: "PH", name: "Philippines" },
    { id: "PL", name: "Poland" },
    { id: "PT", name: "Portugal" },
    { id: "PR", name: "Puerto Rico" },
    { id: "QA", name: "Qatar" },
    { id: "RO", name: "Romania" },
    { id: "RU", name: "Russia" },
    { id: "RW", name: "Rwanda" },
    { id: "KN", name: "Saint Kitts and Nevis" },
    { id: "LC", name: "Saint Lucia" },
    { id: "VC", name: "Saint Vincent and the Grenadines" },
    { id: "WS", name: "Samoa" },
    { id: "SM", name: "San Marino" },
    { id: "ST", name: "São Tomé and Príncipe" },
    { id: "SA", name: "Saudi Arabia" },
    { id: "SN", name: "Senegal" },
    { id: "RS", name: "Serbia" },
    { id: "SC", name: "Seychelles" },
    { id: "SL", name: "Sierra Leone" },
    { id: "SG", name: "Singapore" },
    { id: "SX", name: "Sint Maarten" },
    { id: "SK", name: "Slovakia" },
    { id: "SI", name: "Slovenia" },
    { id: "SB", name: "Solomon Islands" },
    { id: "SO", name: "Somalia" },
    { id: "ZA", name: "South Africa" },
    { id: "SS", name: "South Sudan" },
    { id: "ES", name: "Spain" },
    { id: "LK", name: "Sri Lanka" },
    { id: "SD", name: "Sudan" },
    { id: "SR", name: "Suriname" },
    { id: "SZ", name: "Swaziland" },
    { id: "SE", name: "Sweden" },
    { id: "CH", name: "Switzerland" },
    { id: "SY", name: "Syria" },
    { id: "TW", name: "Taiwan" },
    { id: "TJ", name: "Tajikistan" },
    { id: "TZ", name: "Tanzania" },
    { id: "TH", name: "Thailand" },
    { id: "TG", name: "Togo" },
    { id: "TO", name: "Tonga" },
    { id: "TT", name: "Trinidad and Tobago" },
    { id: "TN", name: "Tunisia" },
    { id: "TR", name: "Turkey" },
    { id: "TM", name: "Turkmenistan" },
    { id: "TV", name: "Tuvalu" },
    { id: "UG", name: "Uganda" },
    { id: "UA", name: "Ukraine" },
    { id: "AE", name: "United Arab Emirates" },
    { id: "UY", name: "Uruguay" },
    { id: "UZ", name: "Uzbekistan" },
    { id: "VU", name: "Vanuatu" },
    { id: "VE", name: "Venezuela" },
    { id: "VN", name: "Vietnam" },
    { id: "VI", name: "Virgin Islands" },
    { id: "YE", name: "Yemen" },
    { id: "ZM", name: "Zambia" },
    { id: "ZW", name: "Zimbabwe" },
  ];

  export const Countries = [
    { label: "🇦🇫 +93", value: "+93" },
    { label: "🇦🇱 +355", value: "+355" },
    { label: "🇩🇿 +213", value: "+213" },
    { label: "🇦🇸 +1684", value: "+1684" },
    { label: "🇦🇩 +376", value: "+376" },
    { label: "🇦🇴 +244", value: "+244" },
    { label: "🇦🇮 +1264", value: "+1264" },
    { label: "🇦🇬 +1268", value: "+1268" },
    { label: "🇦🇷 +54", value: "+54" },
    { label: "🇦🇲 Armenia +374", value: "+374" },
    { label: "🇦🇼 Aruba +297", value: "+297" },
    { label: "🇦🇺 Australia +61", value: "+61" },
    { label: "🇦🇹 Austria +43", value: "+43" },
    { label: "🇦🇿 Azerbaijan +994", value: "+994" },
    { label: "🇧🇸 Bahamas +1242", value: "+1242" },
    { label: "🇧🇭 Bahrain +973", value: "+973" },
    { label: "🇧🇩 Bangladesh +880", value: "+880" },
    { label: "🇧🇧 Barbados +1246", value: "+1246" },
    { label: "🇧🇾 Belarus +375", value: "+375" },
    { label: "🇧🇪 Belgium +32", value: "+32" },
    { label: "🇧🇿 Belize +501", value: "+501" },
    { label: "🇧🇯 Benin +229", value: "+229" },
    { label: "🇧🇲 Bermuda +1441", value: "+1441" },
    { label: "🇧🇹 Bhutan +975", value: "+975" },
    { label: "🇧🇴 Bolivia +591", value: "+591" },
    { label: "🇧🇦 Bosnia and Herzegovina +387", value: "+387" },
    { label: "🇧🇼 Botswana +267", value: "+267" },
    { label: "🇧🇷 Brazil +55", value: "+55" },
    { label: "🇧🇳 Brunei Darussalam +673", value: "+673" },
    { label: "🇧🇬 Bulgaria +359", value: "+359" },
    { label: "🇧🇫 Burkina Faso +226", value: "+226" },
    { label: "🇧🇮 Burundi +257", value: "+257" },
    { label: "🇨🇻 Cabo Verde +238", value: "+238" },
    { label: "🇰🇭 Cambodia +855", value: "+855" },
    { label: "🇨🇲 Cameroon +237", value: "+237" },
    // { label: "🇨🇦 Canada +1", value: "+1" },
    { label: "🇨🇫 Central African Republic +236", value: "+236" },
    { label: "🇹🇩 Chad +235", value: "+235" },
    { label: "🇨🇱 Chile +56", value: "+56" },
    { label: "🇨🇳 China +86", value: "+86" },
    { label: "🇨🇴 Colombia +57", value: "+57" },
    { label: "🇰🇲 Comoros +269", value: "+269" },
    { label: "🇨🇩 Congo (Kinshasa) +243", value: "+243" },
    { label: "🇨🇬 Congo +242", value: "+242" },
    { label: "🇨🇷 Costa Rica +506", value: "+506" },
    { label: "🇨🇮 Côte d'Ivoire +225", value: "+225" },
    { label: "🇭🇷 Croatia +385", value: "+385" },
    { label: "🇨🇺 Cuba +53", value: "+53" },
    { label: "🇨🇾 Cyprus +357", value: "+357" },
    { label: "🇨🇿 Czech Republic +420", value: "+420" },
    { label: "🇩🇰 Denmark +45", value: "+45" },
    { label: "🇩🇯 Djibouti +253", value: "+253" },
    { label: "🇩🇲 Dominica +1767", value: "+1767" },
    { label: "🇩🇴 Dominican Republic +1809", value: "+1809" },
    { label: "🇪🇨 Ecuador +593", value: "+593" },
    { label: "🇪🇬 Egypt +20", value: "+20" },
    { label: "🇸🇻 El Salvador +503", value: "+503" },
    { label: "🇬🇶 Equatorial Guinea +240", value: "+240" },
    { label: "🇪🇷 Eritrea +291", value: "+291" },
    { label: "🇪🇪 Estonia +372", value: "+372" },
    { label: "🇸🇿 Eswatini +268", value: "+268" },
    { label: "🇪🇹 Ethiopia +251", value: "+251" },
    { label: "🇫🇯 Fiji +679", value: "+679" },
    { label: "🇫🇮 Finland +358", value: "+358" },
    { label: "🇫🇷 France +33", value: "+33" },
    { label: "🇬🇦 Gabon +241", value: "+241" },
    { label: "🇬🇲 Gambia +220", value: "+220" },
    { label: "🇬🇪 Georgia +995", value: "+995" },
    { label: "🇩🇪 Germany +49", value: "+49" },
    { label: "🇬🇭 Ghana +233", value: "+233" },
    { label: "🇬🇷 Greece +30", value: "+30" },
    { label: "🇬🇩 Grenada +1473", value: "+1473" },
    { label: "🇬🇹 Guatemala +502", value: "+502" },
    { label: "🇬🇳 Guinea +224", value: "+224" },
    { label: "🇬🇼 Guinea-Bissau +245", value: "+245" },
    { label: "🇬🇾 Guyana +592", value: "+592" },
    { label: "🇭🇹 Haiti +509", value: "+509" },
    { label: "🇭🇳 Honduras +504", value: "+504" },
    { label: "🇭🇰 Hong Kong +852", value: "+852" },
    { label: "🇭🇺 Hungary +36", value: "+36" },
    { label: "🇮🇸 Iceland +354", value: "+354" },
    { label: "🇮🇳 India +91", value: "+91" },
    { label: "🇮🇩 Indonesia +62", value: "+62" },
    { label: "🇮🇷 Iran +98", value: "+98" },
    { label: "🇮🇶 Iraq +964", value: "+964" },
    { label: "🇮🇪 Ireland +353", value: "+353" },
    { label: "🇮🇱 Israel +972", value: "+972" },
    { label: "🇮🇹 Italy +39", value: "+39" },
    { label: "🇯🇲 Jamaica +1876", value: "+1876" },
    { label: "🇯🇵 Japan +81", value: "+81" },
    { label: "🇯🇴 Jordan +962", value: "+962" },
    { label: "🇰🇿 Kazakhstan +7", value: "+7" },
    { label: "🇰🇪 Kenya +254", value: "+254" },
    { label: "🇰🇮 Kiribati +686", value: "+686" },
    { label: "🇰🇼 Kuwait +965", value: "+965" },
    { label: "🇰🇬 Kyrgyzstan +996", value: "+996" },
    { label: "🇱🇦 Laos +856", value: "+856" },
    { label: "🇱🇻 Latvia +371", value: "+371" },
    { label: "🇱🇧 Lebanon +961", value: "+961" },
    { label: "🇱🇸 Lesotho +266", value: "+266" },
    { label: "🇱🇷 Liberia +231", value: "+231" },
    { label: "🇱🇾 Libya +218", value: "+218" },
    { label: "🇱🇮 Liechtenstein +423", value: "+423" },
    { label: "🇱🇹 Lithuania +370", value: "+370" },
    { label: "🇱🇺 Luxembourg +352", value: "+352" },
    { label: "🇲🇴 Macao +853", value: "+853" },
    { label: "🇲🇰 North Macedonia +389", value: "+389" },
    { label: "🇲🇬 Madagascar +261", value: "+261" },
    { label: "🇲🇼 Malawi +265", value: "+265" },
    { label: "🇲🇾 Malaysia +60", value: "+60" },
    { label: "🇲🇻 Maldives +960", value: "+960" },
    { label: "🇲🇱 Mali +223", value: "+223" },
    { label: "🇲🇹 Malta +356", value: "+356" },
    { label: "🇲🇭 Marshall Islands +692", value: "+692" },
    { label: "🇲🇶 Martinique +596", value: "+596" },
    { label: "🇲🇷 Mauritania +222", value: "+222" },
    { label: "🇲🇺 Mauritius +230", value: "+230" },
    { label: "🇲🇽 Mexico +52", value: "+52" },
    { label: "🇫🇲 Micronesia +691", value: "+691" },
    { label: "🇲🇩 Moldova +373", value: "+373" },
    { label: "🇲🇨 Monaco +377", value: "+377" },
    { label: "🇲🇳 Mongolia +976", value: "+976" },
    { label: "🇲🇪 Montenegro +382", value: "+382" },
    { label: "🇲🇦 Morocco +212", value: "+212" },
    { label: "🇲🇿 Mozambique +258", value: "+258" },
    { label: "🇲🇲 Myanmar +95", value: "+95" },
    { label: "🇳🇦 Namibia +264", value: "+264" },
    { label: "🇳🇷 Nauru +674", value: "+674" },
    { label: "🇳🇵 Nepal +977", value: "+977" },
    { label: "🇳🇱 Netherlands +31", value: "+31" },
    { label: "🇳🇨 New Caledonia +687", value: "+687" },
    { label: "🇳🇿 New Zealand +64", value: "+64" },
    { label: "🇳🇮 Nicaragua +505", value: "+505" },
    { label: "🇳🇪 +227", value: "+227" },
    { label: "🇳🇬 +234", value: "+234" },
    { label: "🇰🇵 North Korea +850", value: "+850" },
    { label: "🇳🇴 Norway +47", value: "+47" },
    { label: "🇴🇲 Oman +968", value: "+968" },
    { label: "🇵🇰 Pakistan +92", value: "+92" },
    { label: "🇵🇼 Palau +680", value: "+680" },
    { label: "🇵🇦 Panama +507", value: "+507" },
    { label: "🇵🇬 Papua New Guinea +675", value: "+675" },
    { label: "🇵🇾 Paraguay +595", value: "+595" },
    { label: "🇵🇪 Peru +51", value: "+51" },
    { label: "🇵🇭 Philippines +63", value: "+63" },
    { label: "🇵🇱 Poland +48", value: "+48" },
    { label: "🇵🇹 Portugal +351", value: "+351" },
    { label: "🇶🇦 Qatar +974", value: "+974" },
    { label: "🇷🇴 Romania +40", value: "+40" },
    { label: "🇷🇺 Russia +7", value: "+7" },
    { label: "🇷🇼 Rwanda +250", value: "+250" },
    { label: "🇰🇳 Saint Kitts and Nevis +1869", value: "+1869" },
    { label: "🇱🇨 Saint Lucia +1758", value: "+1758" },
    { label: "🇻🇨 Saint Vincent and the Grenadines +1784", value: "+1784" },
    { label: "🇼🇸 Samoa +685", value: "+685" },
    { label: "🇸🇲 San Marino +378", value: "+378" },
    { label: "🇸🇹 Sao Tome and Principe +239", value: "+239" },
    { label: "🇸🇦 Saudi Arabia +966", value: "+966" },
    { label: "🇸🇳 Senegal +221", value: "+221" },
    { label: "🇷🇸 Serbia +381", value: "+381" },
    { label: "🇸🇨 Seychelles +248", value: "+248" },
    { label: "🇸🇱 Sierra Leone +232", value: "+232" },
    { label: "🇸🇬 Singapore +65", value: "+65" },
    { label: "🇸🇽 Sint Maarten +1721", value: "+1721" },
    { label: "🇸🇰 Slovakia +421", value: "+421" },
    { label: "🇸🇮 Slovenia +386", value: "+386" },
    { label: "🇸🇧 Solomon Islands +677", value: "+677" },
    { label: "🇸🇴 Somalia +252", value: "+252" },
    { label: "🇿🇦 South Africa +27", value: "+27" },
    { label: "🇰🇷 South Korea +82", value: "+82" },
    { label: "🇸🇸 South Sudan +211", value: "+211" },
    { label: "🇪🇸 Spain +34", value: "+34" },
    { label: "🇱🇰 Sri Lanka +94", value: "+94" },
    { label: "🇸🇩 Sudan +249", value: "+249" },
    { label: "🇸🇷 Suriname +597", value: "+597" },
    { label: "🇸🇪 Sweden +46", value: "+46" },
    { label: "🇨🇭 Switzerland +41", value: "+41" },
    { label: "🇸🇾 Syria +963", value: "+963" },
    { label: "🇹🇼 Taiwan +886", value: "+886" },
    { label: "🇹🇯 Tajikistan +992", value: "+992" },
    { label: "🇹🇿 Tanzania +255", value: "+255" },
    { label: "🇹🇭 Thailand +66", value: "+66" },
    { label: "🇹🇱 Timor-Leste +670", value: "+670" },
    { label: "🇹🇬 Togo +228", value: "+228" },
    { label: "🇹🇴 Tonga +676", value: "+676" },
    { label: "🇹🇹 Trinidad and Tobago +1868", value: "+1868" },
    { label: "🇹🇳 Tunisia +216", value: "+216" },
    { label: "🇹🇷 Turkey +90", value: "+90" },
    { label: "🇹🇲 Turkmenistan +993", value: "+993" },
    { label: "🇹🇻 Tuvalu +688", value: "+688" },
    { label: "🇺🇬 Uganda +256", value: "+256" },
    { label: "🇺🇦 Ukraine +380", value: "+380" },
    { label: "🇦🇪 United Arab Emirates +971", value: "+971" },
    { label: "🇬🇧 United Kingdom +44", value: "+44" },
    { label: "🇺🇸 United States +1", value: "+1" },
    { label: "🇺🇾 Uruguay +598", value: "+598" },
    { label: "🇺🇿 Uzbekistan +998", value: "+998" },
    { label: "🇻🇺 Vanuatu +678", value: "+678" },
    { label: "🇻🇪 Venezuela +58", value: "+58" },
    { label: "🇻🇳 Vietnam +84", value: "+84" },
    { label: "🇾🇪 Yemen +967", value: "+967" },
    { label: "🇿🇲 Zambia +260", value: "+260" },
    { label: "🇿🇼 Zimbabwe +263", value: "+263" },
  ];

  export const worldCountries = [
    { id: "AF", label: "Afghanistan", value: "+93" },
    { id: "AL", label: "Albania", value: "+355" },
    { id: "DZ", label: "Algeria", value: "+213" },
    { id: "AS", label: "American Samoa", value: "+1-684" },
    { id: "AD", label: "Andorra", value: "+376" },
    { id: "AO", label: "Angola", value: "+244" },
    { id: "AI", label: "Anguilla", value: "+1-264" },
    { id: "AG", label: "Antigua and Barbuda", value: "+1-268" },
    { id: "AR", label: "Argentina", value: "+54" },
    { id: "AM", label: "Armenia", value: "+374" },
    { id: "AW", label: "Aruba", value: "+297" },
    { id: "AU", label: "Australia", value: "+61" },
    { id: "AT", label: "Austria", value: "+43" },
    { id: "AZ", label: "Azerbaijan", value: "+994" },
    { id: "BS", label: "Bahamas", value: "+1-242" },
    { id: "BH", label: "Bahrain", value: "+973" },
    { id: "BD", label: "Bangladesh", value: "+880" },
    { id: "BB", label: "Barbados", value: "+1-246" },
    { id: "BY", label: "Belarus", value: "+375" },
    { id: "BE", label: "Belgium", value: "+32" },
    { id: "BZ", label: "Belize", value: "+501" },
    { id: "BJ", label: "Benin", value: "+229" },
    { id: "BM", label: "Bermuda", value: "+1-441" },
    { id: "BT", label: "Bhutan", value: "+975" },
    { id: "BO", label: "Bolivia", value: "+591" },
    { id: "BA", label: "Bosnia and Herzegovina", value: "+387" },
    { id: "BW", label: "Botswana", value: "+267" },
    { id: "BR", label: "Brazil", value: "+55" },
    { id: "IO", label: "British Indian Ocean Territory", value: "+246" },
    { id: "VG", label: "British Virgin Islands", value: "+1-284" },
    { id: "BN", label: "Brunei", value: "+673" },
    { id: "BG", label: "Bulgaria", value: "+359" },
    { id: "BF", label: "Burkina Faso", value: "+226" },
    { id: "BI", label: "Burundi", value: "+257" },
    { id: "KH", label: "Cambodia", value: "+855" },
    { id: "CM", label: "Cameroon", value: "+237" },
    { id: "CA", label: "Canada", value: "+1" },
    { id: "CV", label: "Cape Verde", value: "+238" },
    { id: "KY", label: "Cayman Islands", value: "+1-345" },
    { id: "CF", label: "Central African Republic", value: "+236" },
    { id: "TD", label: "Chad", value: "+235" },
    { id: "CL", label: "Chile", value: "+56" },
    { id: "CN", label: "China", value: "+86" },
    { id: "CO", label: "Colombia", value: "+57" },
    { id: "KM", label: "Comoros", value: "+269" },
    { id: "CG", label: "Congo (Brazzaville)", value: "+242" },
    { id: "CD", label: "Congo (Kinshasa)", value: "+243" },
    { id: "CR", label: "Costa Rica", value: "+506" },
    { id: "CI", label: "Côte d’Ivoire", value: "+225" },
    { id: "HR", label: "Croatia", value: "+385" },
    { id: "CU", label: "Cuba", value: "+53" },
    { id: "CY", label: "Cyprus", value: "+357" },
    { id: "CZ", label: "Czech Republic", value: "+420" },
    { id: "DK", label: "Denmark", value: "+45" },
    { id: "DJ", label: "Djibouti", value: "+253" },
    { id: "DM", label: "Dominica", value: "+1-767" },
    { id: "DO", label: "Dominican Republic", value: "+1-809" },
    { id: "EC", label: "Ecuador", value: "+593" },
    { id: "EG", label: "Egypt", value: "+20" },
    { id: "SV", label: "El Salvador", value: "+503" },
    { id: "GQ", label: "Equatorial Guinea", value: "+240" },
    { id: "ER", label: "Eritrea", value: "+291" },
    { id: "EE", label: "Estonia", value: "+372" },
    { id: "ET", label: "Ethiopia", value: "+251" },
    { id: "FJ", label: "Fiji", value: "+679" },
    { id: "FI", label: "Finland", value: "+358" },
    { id: "FR", label: "France", value: "+33" },
    { id: "GA", label: "Gabon", value: "+241" },
    { id: "GM", label: "Gambia", value: "+220" },
    { id: "GE", label: "Georgia", value: "+995" },
    { id: "DE", label: "Germany", value: "+49" },
    { id: "GH", label: "Ghana", value: "+233" },
    { id: "GR", label: "Greece", value: "+30" },
    { id: "GD", label: "Grenada", value: "+1-473" },
    { id: "GT", label: "Guatemala", value: "+502" },
    { id: "GN", label: "Guinea", value: "+224" },
    { id: "GW", label: "Guinea-Bissau", value: "+245" },
    { id: "GY", label: "Guyana", value: "+592" },
    { id: "HT", label: "Haiti", value: "+509" },
    { id: "HN", label: "Honduras", value: "+504" },
    { id: "HK", label: "Hong Kong", value: "+852" },
    { id: "HU", label: "Hungary", value: "+36" },
    { id: "IS", label: "Iceland", value: "+354" },
    { id: "IN", label: "India", value: "+91" },
    { id: "ID", label: "Indonesia", value: "+62" },
    { id: "IR", label: "Iran", value: "+98" },
    { id: "IQ", label: "Iraq", value: "+964" },
    { id: "IE", label: "Ireland", value: "+353" },
    { id: "IL", label: "Israel", value: "+972" },
    { id: "IT", label: "Italy", value: "+39" },
    { id: "JM", label: "Jamaica", value: "+1-876" },
    { id: "JP", label: "Japan", value: "+81" },
    { id: "JO", label: "Jordan", value: "+962" },
    { id: "KZ", label: "Kazakhstan", value: "+7" },
    { id: "KE", label: "Kenya", value: "+254" },
    { id: "KI", label: "Kiribati", value: "+686" },
    { id: "KW", label: "Kuwait", value: "+965" },
    { id: "KG", label: "Kyrgyzstan", value: "+996" },
    { id: "LA", label: "Laos", value: "+856" },
    { id: "LV", label: "Latvia", value: "+371" },
    { id: "LB", label: "Lebanon", value: "+961" },
    { id: "LS", label: "Lesotho", value: "+266" },
    { id: "LR", label: "Liberia", value: "+231" },
    { id: "LY", label: "Libya", value: "+218" },
    { id: "LI", label: "Liechtenstein", value: "+423" },
    { id: "LT", label: "Lithuania", value: "+370" },
    { id: "LU", label: "Luxembourg", value: "+352" },
    { id: "MO", label: "Macau", value: "+853" },
    { id: "MK", label: "Macedonia", value: "+389" },
    { id: "MG", label: "Madagascar", value: "+261" },
    { id: "MW", label: "Malawi", value: "+265" },
    { id: "MY", label: "Malaysia", value: "+60" },
    { id: "MV", label: "Maldives", value: "+960" },
    { id: "ML", label: "Mali", value: "+223" },
    { id: "MT", label: "Malta", value: "+356" },
    { id: "MH", label: "Marshall Islands", value: "+692" },
    { id: "MR", label: "Mauritania", value: "+222" },
    { id: "MU", label: "Mauritius", value: "+230" },
    { id: "MX", label: "Mexico", value: "+52" },
    { id: "FM", label: "Micronesia", value: "+691" },
    { id: "MD", label: "Moldova", value: "+373" },
    { id: "MC", label: "Monaco", value: "+377" },
    { id: "MN", label: "Mongolia", value: "+976" },
    { id: "ME", label: "Montenegro", value: "+382" },
    { id: "MS", label: "Montserrat", value: "+1-664" },
    { id: "MA", label: "Morocco", value: "+212" },
    { id: "MZ", label: "Mozambique", value: "+258" },
    { id: "MM", label: "Myanmar", value: "+95" },
    { id: "NA", label: "Namibia", value: "+264" },
    { id: "NR", label: "Nauru", value: "+674" },
    { id: "NP", label: "Nepal", value: "+977" },
    { id: "NL", label: "Netherlands", value: "+31" },
    { id: "NZ", label: "New Zealand", value: "+64" },
    { id: "NI", label: "Nicaragua", value: "+505" },
    { id: "NE", label: "Niger", value: "+227" },
    { id: "NG", label: "Nigeria", value: "+234" },
    { id: "NU", label: "Niue", value: "+683" },
    { id: "KP", label: "North Korea", value: "+850" },
    { id: "NO", label: "Norway", value: "+47" },
    { id: "OM", label: "Oman", value: "+968" },
    { id: "PK", label: "Pakistan", value: "+92" },
    { id: "PW", label: "Palau", value: "+680" },
    { id: "PA", label: "Panama", value: "+507" },
    { id: "PG", label: "Papua New Guinea", value: "+675" },
    { id: "PY", label: "Paraguay", value: "+595" },
    { id: "PE", label: "Peru", value: "+51" },
    { id: "PH", label: "Philippines", value: "+63" },
    { id: "PL", label: "Poland", value: "+48" },
    { id: "PT", label: "Portugal", value: "+351" },
    { id: "QA", label: "Qatar", value: "+974" },
    { id: "RO", label: "Romania", value: "+40" },
    { id: "RU", label: "Russia", value: "+7" },
    { id: "RW", label: "Rwanda", value: "+250" },
    { id: "KN", label: "Saint Kitts and Nevis", value: "+1-869" },
    { id: "LC", label: "Saint Lucia", value: "+1-758" },
    { id: "VC", label: "Saint Vincent and the Grenadines", value: "+1-784" },
    { id: "WS", label: "Samoa", value: "+685" },
    { id: "SM", label: "San Marino", value: "+378" },
    { id: "ST", label: "São Tomé and Príncipe", value: "+239" },
    { id: "SA", label: "Saudi Arabia", value: "+966" },
    { id: "SN", label: "Senegal", value: "+221" },
    { id: "RS", label: "Serbia", value: "+381" },
    { id: "SC", label: "Seychelles", value: "+248" },
    { id: "SL", label: "Sierra Leone", value: "+232" },
    { id: "SG", label: "Singapore", value: "+65" },
    { id: "SK", label: "Slovakia", value: "+421" },
    { id: "SI", label: "Slovenia", value: "+386" },
    { id: "SB", label: "Solomon Islands", value: "+677" },
    { id: "SO", label: "Somalia", value: "+252" },
    { id: "ZA", label: "South Africa", value: "+27" },
    { id: "KR", label: "South Korea", value: "+82" },
    { id: "SS", label: "South Sudan", value: "+211" },
    { id: "ES", label: "Spain", value: "+34" },
    { id: "LK", label: "Sri Lanka", value: "+94" },
    { id: "SD", label: "Sudan", value: "+249" },
    { id: "SR", label: "Suriname", value: "+597" },
    { id: "SZ", label: "Swaziland", value: "+268" },
    { id: "SE", label: "Sweden", value: "+46" },
    { id: "CH", label: "Switzerland", value: "+41" },
    { id: "SY", label: "Syria", value: "+963" },
    { id: "TW", label: "Taiwan", value: "+886" },
    { id: "TJ", label: "Tajikistan", value: "+992" },
    { id: "TZ", label: "Tanzania", value: "+255" },
    { id: "TH", label: "Thailand", value: "+66" },
    { id: "TL", label: "Timor-Leste", value: "+670" },
    { id: "TG", label: "Togo", value: "+228" },
    { id: "TO", label: "Tonga", value: "+676" },
    { id: "TT", label: "Trinidad and Tobago", value: "+1-868" },
    { id: "TN", label: "Tunisia", value: "+216" },
    { id: "TR", label: "Turkey", value: "+90" },
    { id: "TM", label: "Turkmenistan", value: "+993" },
    { id: "TV", label: "Tuvalu", value: "+688" },
    { id: "UG", label: "Uganda", value: "+256" },
    { id: "UA", label: "Ukraine", value: "+380" },
    { id: "AE", label: "United Arab Emirates", value: "+971" },
    { id: "GB", label: "United Kingdom", value: "+44" },
    { id: "US", label: "United States", value: "+1" },
    { id: "UY", label: "Uruguay", value: "+598" },
    { id: "UZ", label: "Uzbekistan", value: "+998" },
    { id: "VU", label: "Vanuatu", value: "+678" },
    { id: "VA", label: "Vatican City", value: "+379" },
    { id: "VE", label: "Venezuela", value: "+58" },
    { id: "VN", label: "Vietnam", value: "+84" },
    { id: "YE", label: "Yemen", value: "+967" },
    { id: "ZM", label: "Zambia", value: "+260" },
    { id: "ZW", label: "Zimbabwe", value: "+263" },
  ];
  
export const waitFor =(duration?:number) =>{
  return new Promise(resolve => setTimeout(resolve, duration|| 1000));
}

// Toast and notification constants
export const TOAST_DURATION = 4000;
export const SUCCESS_NAVIGATION_DELAY = 2000;

export const COLLAGE_SKIA_ENABLED = true;