import { StyleSheet } from "react-native";
import { primaryBase } from "../../constants/Colors";

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    marginTop: 20,
  },
  modalContent: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 42,
    gap: 24,
  },
  closeButton: {
    position: "absolute",
    top: 20,
    right: 20,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 4,
  },
  header: {
    alignItems: "center",
    gap: 4,
    marginTop: 40,
  },
  title: {
    fontSize: 18,
    lineHeight: 27,
    textAlign: "center",
    color: "#212b36",
    fontFamily: "DMSans-Bold",
    fontWeight: "600",
  },
  welcomeTitle: {
    fontSize: 18,
    lineHeight: 27,
    textAlign: "center",
    color: "#212b36",
    fontFamily: "DMSans-Bold",
    fontWeight: "600",
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
    color: "#637381",
    fontFamily: "DMSans-Regular",
  },
  emailDisplaySection: {
    gap: 16,
  },
  emailDisplayContainer: {
    backgroundColor: "rgba(145, 158, 171, 0.08)",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 16,
    height: 53,
    justifyContent: "center",
  },
  emailLabel: {
    fontSize: 12,
    lineHeight: 12,
    fontWeight: "500",
    fontFamily: "DMSans-Medium",
    color: "#637381",
    marginBottom: 4,
  },
  emailValue: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: "DMSans-SemiBold",
    fontWeight: "600",
    color: "#212b36",
  },
  inputSection: {
    gap: 16,
  },
  inputContainer: {
    flexDirection: "row",
    backgroundColor: "rgba(145, 158, 171, 0.08)",
    borderRadius: 8,
    height: 53,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  input: {
    flex: 1,
    fontSize: 14,
    fontFamily: "DMSans-SemiBold",
    fontWeight: "600",
    color: "#212b36",
    paddingVertical: 16,
  },
  placeholder: {
    position: "absolute",
    left: 12,
    fontSize: 12,
    lineHeight: 12,
    fontWeight: "500",
    fontFamily: "DMSans-Medium",
    color: "#637381",
    backgroundColor: "transparent",
    zIndex: 1,
  },
  placeholderFocused: {
    top: 8,
    fontSize: 12,
    color: "#637381",
  },
  iconContainer: {
    justifyContent: "center",
    alignItems: "center",
    width: 40,
    height: 40,
  },
  errorBorder: {
    borderWidth: 1,
    borderColor: "red",
  },
  errorText: {
    color: "red",
    fontSize: 12,
    fontFamily: "DMSans-Regular",
  },
  forgotPasswordContainer: {
    alignSelf: "flex-end",
    paddingVertical: 4,
  },
  forgotPasswordText: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: "DMSans-Regular",
    color: "#d4313e",
    textAlign: "right",
  },
  buttonSection: {
    marginTop: 10,
  },
  continueButton: {
    backgroundColor: primaryBase,
  },
  loginButton: {
    backgroundColor: primaryBase,
  },
  // Signup Screen Styles
  signupContainer: {
    flex: 1,
    backgroundColor: "#fff",
  },
  signupScrollContent: {
    flexGrow: 1,
  },
  signupContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 42,
    gap: 24,
  },
  signupHeader: {
    alignItems: "center",
    gap: 4,
    marginTop: 40,
  },
  signupTitle: {
    fontSize: 18,
    lineHeight: 27,
    textAlign: "center",
    color: "#212b36",
    fontFamily: "DMSans-Bold",
    fontWeight: "600",
  },
  signupSubtitle: {
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
    color: "#637381",
    fontFamily: "DMSans-Regular",
  },
  nameRow: {
    flexDirection: "row",
    gap: 12,
  },
  nameInput: {
    flex: 1,
    backgroundColor: "#F5F6F7",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    height: 50,
  },
  nameInputText: {
    fontSize: 15,
    color: "#222",
    fontFamily: "DMSansRegular",
    padding: 0,
    backgroundColor: "transparent",
  },
  countryInput: {
    backgroundColor: "#F5F6F7",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    height: 50,
    flexDirection: "row",
    alignItems: "center",
  },
  countryText: {
    fontSize: 15,
    color: "#222",
    fontFamily: "DMSansRegular",
    flex: 1,
  },
  phoneInput: {
    backgroundColor: "#F5F6F7",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    height: 50,
    flexDirection: "row",
    alignItems: "center",
  },
  phonePrefix: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 8,
  },
  dialingCode: {
    marginLeft: 6,
    fontSize: 15,
    color: "#222",
    fontFamily: "DMSansRegular",
    minWidth: 36,
  },
  phoneInputText: {
    fontSize: 15,
    color: "#222",
    fontFamily: "DMSansRegular",
    padding: 0,
    backgroundColor: "transparent",
    flex: 1,
  },
  termsContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 20,
  },
  termsTextContainer: {
    flex: 1,
    marginLeft: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
  },
  termsLinkContainer: {
    // No additional styling needed, just for TouchableOpacity
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: "#98A2B3",
    // marginRight: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  checkboxChecked: {
    borderColor: "#D4313E",
    backgroundColor: "#D4313E",
  },
  checkmark: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  termsText: {
    fontSize: 13,
    color: "#222",
    fontFamily: "DMSansRegular",
    lineHeight: 18,
  },
  termsLink: {
    color: "#D4313E",
    fontWeight: "500",
    fontFamily: "DMSansRegular",
  },
  termsErrorText: {
    color: '#FF3B4A',
    fontSize: 12,
    marginTop: 4,
    marginLeft: 2,
    fontFamily: 'DMSansMedium',
  },
  termsModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  termsModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    width: '100%',
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  termsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  termsModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
    fontFamily: 'DMSansBold',
  },
  termsModalCloseButton: {
    padding: 4,
  },
  termsModalBody: {
    padding: 20,
    maxHeight: 400,
  },
  termsModalText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#374151',
    fontFamily: 'DMSansRegular',
  },
  termsModalSubtitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
    fontFamily: 'DMSansBold',
    marginTop: 16,
    marginBottom: 8,
  },
  signupButtonSection: {
    marginTop: 18,
    marginBottom: 8,
  },
  signupButton: {
    backgroundColor: primaryBase,
  },
});
